services:
  znc:
    image: znc:latest
    ports:
      - "6698:6698"
    volumes:
      - znc-data:/znc-data
      - ./configs:/znc-data/configs
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./handle_certs.sh:/startup-sequence/19-handle_certs.sh:ro
    restart: unless-stopped
#    command: '-D'

volumes:
  znc-data:
